perkeep/perkeep

pkg/test/dockertest/docker.go

The haveImage function was only able to work with image names of the "repository" form, and not "repository:tag" form, which was not convenient when we actually want a specific tag of an image, such as "mysql:8".

test/dockertest: allow the <repository:tag> syntax for images

---

server/perkeepd/ui/blob_item_video.css

server/perkeepd/ui: Fix blob item video play button styling

---

server/perkeepd/ui/audio_detail.css
server/perkeepd/ui/audio_detail.js
server/perkeepd/ui/blob_item_audio.css
server/perkeepd/ui/blob_item_audio_content.js
server/perkeepd/ui/index.css
server/perkeepd/ui/index.html
server/perkeepd/ui/index.js

Adds audio support to the web UI

server/perkeepd/ui: Implement blob audio

---

Dockerfile
make.go
misc/docker/go/Dockerfile

Also update to Go1.13.5
Fixes #1286

make.go: add -offline flag

---

app/publisher/js/file.go

app/publisher/js: support for sha224 hashes

---

misc/docker/dock.go
misc/docker/server/build-perkeep-server.go
misc/release/build-binaries.go
misc/release/make-release.go
misc/release/zip-source.go

Various fixes to bring them up to date, and to make them work on MacOS.

misc: update release tools

---

pkg/blobserver/encrypt/encrypt.go
pkg/blobserver/encrypt/encrypt_test.go

picked-up a small todo in the code.

encrypt.go: check keyFile permissions

---

cmd/pk/list.go

filter blobs by schema type. I piped to grep a couple time but this is a bit better.
Also changed `blob type` for `schema blob type` because that's what we call them according to [docs/terms](https://perkeep.org/doc/terms).

cmd/pk/list: filter by type

---

.github/workflows/tests-macos.yml
go.mod
go.sum

Now we have a green build on linux, macos and windows :tada:

CI: test on macOS

---

server/perkeepd/ui/blobref.js
server/perkeepd/ui/goui/main.go
server/perkeepd/ui/index.js

Almost done. Only the geo thigs are left and there won't be any go in the main UI.

IsBlobRef: go -> JS

---

internal/images/docker.go

images/haveImageID: use docker images, not inspect
Docker inspect will not exit 0 if no version of the image is available
on the machine, leading to the method failing. There is no flag to
adjust this in docker inspect, the only solution would be to parse the
error message but that would be fragile.
Instead, we opt to use `docker images` which has a very similar output
with the exception that it will list all tags available for that image
and that it will not fail on absent images.
This fixed HEIC thumbnails on my machine as I don't have a recent verion of imagemagick.
Initially I submitted [another PR](https://github.com/perkeep/perkeep/pull/1370) trying to adjust the `docker inspect` flags but then I realised that my PR had fixed nothing, it just started working because I had manually …

images/haveImageID: use docker images, not inspect

---

internal/httputil/httputil.go

This PR removes the `io.LimitReader` that was throwing away server responses beyond an 8MB threshold.
The presence of that `LimitReader` was causing `pk-mount` to fail for me (with an unexpected EOF in JSON decoding) [here](https://github.com/perkeep/perkeep/blob/9a1336816afdfcf36ae0ec3705e5ae4053748f10/pkg/fs/mut.go#L139-L142) on directories with large subtrees.

internal/httputil: do not throw away server responses beyond 8MB

---

website/README.md

fix bug: typo

---

pkg/blobserver/gethandler/get.go

This PR removes some unused test code from `pkg/blobserver/gethandler.go`

blobserver: remove unused code from gethandler

---

pkg/fs/fs_test.go
pkg/fs/mut.go

This PR fixes a bug in pkg/fs/mut.go where the size attribute was ignored on truncations.
Fixes #1218

fuse: fix truncation of files

---

pkg/blobserver/encrypt/encrypt.go
pkg/blobserver/encrypt/encrypt_test.go

This fixes a race condition when fetching blobs from an encrypted blob server

encrypt: fix race condition

---

pkg/index/receive.go

minor cleanup of reindex logic

index: minor cleanup

---

pkg/index/index.go
pkg/index/indextest/tests.go
pkg/index/kvfile_test.go
pkg/index/leveldb_test.go
pkg/index/mysql_test.go
pkg/index/receive.go

* remove scaffolding for #756 after it was fixed
* cleanup redundant test ( Reindex and ShowReindexRace )

index: cleanup after #756 was fixed

---

pkg/test/integration/upload_test.go

Pretty random PR but while checking out `serverinit` i found it imported in integration tests which feels weird since we already have perkeepd running with the "World" struct.

tests: clean up upload test

---

clients/curl/example.sh

It took me a while to figure this out, perhaps it will help other people to have an example

demonstrate query using curl

---

pkg/schema/blob.go
pkg/schema/schema.go
pkg/schema/schema_test.go

Alternative proposal for #1645

schema: simplify parseSuperset

---

server/perkeepd/ui/map.js

See: https://github.com/openstreetmap/operations/issues/737

Update map.js to use correct tile.osm.org URL

---

Dockerfile.website
Makefile
fly.toml
website/pk-web/contributors.go

Sadly I did this all once (and more completely) but then lost the commit. So this is a re-do. The sharing demo stuff isn't yet complete.
Updates #1658 etc

website: move to Fly

---

app/publisher/zip.go
internal/osutil/gce/gce.go
misc/docker/dock.go
misc/release/make-release.go
pkg/blobserver/gethandler/get_test.go
pkg/importer/gphotos/download.go
pkg/importer/gphotos/gphotos.go
pkg/importer/importer_test.go
pkg/importer/twitter/twitter.go
pkg/sorted/mysql/cloudsql.go
server/perkeepd/logging.go

(Originally from https://github.com/perkeep/perkeep/pull/1648)

all: fix or disable staticcheck deprecations

---

pkg/blobserver/azure/azure_test.go
pkg/blobserver/blobpacked/blobpacked_test.go
pkg/blobserver/cond/cond_test.go
pkg/blobserver/diskpacked/diskpacked_test.go
pkg/blobserver/diskpacked/stream_test.go
pkg/blobserver/encrypt/encrypt_test.go
pkg/blobserver/google/cloudstorage/cloudstorage_test.go
pkg/blobserver/google/drive/drive_test.go
pkg/blobserver/localdisk/localdisk_test.go
pkg/blobserver/memory/mem_test.go
pkg/blobserver/mongo/mongo_test.go
pkg/blobserver/namespace/ns_test.go
pkg/blobserver/overlay/overlay_test.go
pkg/blobserver/proxycache/proxycache_test.go
pkg/blobserver/replica/replica_test.go
pkg/blobserver/s3/s3_test.go
pkg/blobserver/sftp/sftp_test.go
pkg/blobserver/shard/shard_test.go
pkg/blobserver/storagetest/storagetest.go
pkg/blobserver/union/union_test.go
pkg/index/indextest/tests.go
pkg/index/kvfile_test.go
pkg/index/leveldb_test.go
pkg/index/mongo_test.go
pkg/index/mysql_test.go
pkg/index/postgres_test.go
pkg/test/fetcher_test.go

Signed-off-by: Brad Fitzpatrick <brad@danga.com>

all: use (*testing.T).Cleanup, simplify test helper signatures

---

cmd/pk-put/files.go
cmd/pk-put/init.go
cmd/pk-put/kvcache.go
cmd/pk-put/permanode.go
cmd/pk/dp_idx_rebuild.go
cmd/pk/dumpconfig.go
cmd/pk/whoami.go

cmd/...: fix staticcheck warnings

---

.github/workflows/tests-lint.yaml
.github/workflows/tests-linux.yml
.github/workflows/tests-macos.yml
.github/workflows/tests-tidy.yaml
.github/workflows/tests-windows.yml

No need for the symlink to `~/go/src/perkeep.org` anymore

.workflows: update github actions
