doc/server-config.md

This hadn't been clear to me as a user getting started.

docs/server-config: mention diskpacked perf trade-off.

---

doc/protocol/blob-stat.md
doc/protocol/blob-upload.md

Which has been deprecated for some time now; the references to it really
date the documents.

docs: remove references to SPDY

---

server/perkeepd/ui/browser_view_detail.js
server/perkeepd/ui/index.js

This just generalizes PdfDetail to also recognize text/plain. It has
been renamed BrowserViewDetail to reflect its more general nature.
Adding more formats will now be trivial: just add entries to the
`supportedMimeTypes` array.

Web UI: viewer for plain text files.

---

doc/arch.md

The link in the docs seems to be broken

doc: fix arch.md content 

---

doc/README.md

#Issue: 
The link pointing to "camlistore.org" will redirect back to "perkeep.org" anyways, so updated with relative link.
#Change:
Updated "Contributing" link from "https://camlistore.org/doc/contributing" to "/code#contributing".

doc/readme: Updated Link

---

doc/compare.md
doc/release/0.10.html

Removes cloud launcher documentation.
Cloud launcher was removed in c9f78d02adf9740f3b8d403a1418554293cc9f41

Remove cloud launcher from doc

---

doc/todo/README.md

doc/todo: fix link, now on github

---

go.mod
go.sum

Let's encrypt doesn't work with the old acme API anymore. The latest version of "x/crypto" fixes that.
Error messages:
```
acme/autocert: missing certificate
403 urn:acme:error:unauthorized: Error creating new authz :: Validations for new domains are disabled in the V1 API (https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430)
```
See:https://go-review.googlesource.com/c/crypto/+/200638
I ran `go get -u golang.org/x/crypto` to update the module. Tests pass with devcam and my server got Let's Encrypt working again.

go.mod: update "x/crypto" to support latest acme API

---

pkg/index/doc.go

Just `Storage` was confusing with `blobserver.Storage`. Let's be specific!

index: based on sorted.KeyValue

---

pkg/blobserver/encrypt/encrypt.go

I have also validated that it renders fine on pk-web:

blobserver/encrypt: document low-level config

---

doc/schema/bytes.md

I confirmed this by looking at schema.go:
https://github.com/perkeep/perkeep/blob/4b2ae528420fe68a2b95d7d5fc7e3f4490c4d91e/pkg/schema/schema.go#L772
I was wondering what a size-only part could possibly mean.

bytes.md: part must contain BlobRef or BytesRef

---

doc/schema/README.md

The Go implementation does this already, and it should be part of the spec so that identifying schema blobs is easier.

docs: standardize on <=1MB schema blobs

---

doc/storage-examples.md

Closes #1338 (not 100% certain its the same issue as I had but probably)
Pretty sure this is needed, both from experience and from trying just now:
```
2021/01/01 22:49:52 Caught panic installer handlers: error instantiating storage for prefix "/sto-s3/", type "s3": s3: could not determine endpoint: AccessDenied: Access Denied
```
This has to do with `GetBucketLocation/ListBuckets` that must be granted on the bucket itself and not on the objects.
Cheers,

storage-examples: grant permissions on the bucket

---

doc/server-config.md

AFAIK this was false. `packRelated` affects `s3`, `b2` and `googlecloudstorage`.
It isn't supported on some other storage types like `memoryStorage` or  `googledrive` but it will raise errors so the user will know.

server-config: packRelated doesn't need blobPath

---

pkg/serverinit/genconfig.go
pkg/serverinit/testdata/packrelated_replicated-want.json
pkg/serverinit/testdata/packrelated_replicated.json

closes #1330
Cloud-backed storage currently does not use blobpacked
if they are a replica. This causes issues if they become
the main storage.
Example use case where this would cause issues:
- Create a configuration with s3, blobPath, and packRelated.
- Add objects
- Remove blobPath
- `pk list`
- All blobs are gone because the s3-only config uses blobpacked
but the s3 replica was not.
Let me know if there is something I overlooked! I think this reduces friction with using the simple configuration.

genconfig: support blobpacked in cloud replicas

---

pkg/index/doc.go

Small nits I noticed while reading pkg/index
- Document that we use an '|indexed' suffix in the 'have:' key to mark
indexed blobs.
- Don't refer to GetOwnerClaims. This method no longer exists and was
replaced by AppendClaims. Don't bother naming the exact Index
interface method this key serves but instead focus on explaining what
information we store in that key.

index: small docs improvements

---

doc/storage-examples.md
go.mod
go.sum
pkg/blobserver/b2/b2.go

- Add documentation in storage-examples for using Perkeep with b2 as a
storage backend. The documentation uses the new API terminology:
AccountID is no longer a thing in the Backblaze web console.
- Replace FiloSottile/b2 by perkeep/b2 where we host a copy of
clgillis's Pull Request[1]. We can point to the original project
again as soon as it is merged.
Note that I haven't updated the vendor directory and it seems that
`go mod vendor` updates way more things that are also outdated in the
master branch, so I will leave that as an exercise to whoever has
commit access :).
Before this Pull Request, launching the b2 storage would error with the
following error message:
```
Error parsing config: Caught panic: error instantiating storage for prefix "/sto-b2/", type "b2": Post …
```

b2: document example + point to perkeep/b2 fork

---

server/perkeepd/ui/header.js
server/perkeepd/ui/index.js

handleAbout: move to index.js
All other buttons from the top menu are implemented like this, and
the go ones were an exception. This isn't in go anymore so we should
just use `getMenuItem_` like all others and implement the event
handler in index.js.

handleAbout: move to index.js

---

app/publisher/main.go
app/publisher/zip.go
cmd/pk-get/get.go
cmd/pk-get/graph.go
cmd/pk-put/files.go
cmd/pk-put/put.go
cmd/pk/list.go
cmd/pk/makestatic.go
pkg/blobserver/blobpacked/blobpacked.go
pkg/client/upload.go
pkg/fs/fs.go
pkg/index/corpus.go
pkg/index/index.go
pkg/index/indextest/tests.go
pkg/index/receive.go
pkg/index/sniff.go
pkg/schema/blob.go
pkg/schema/fileread_test.go
pkg/schema/filewriter.go
pkg/schema/schema.go
pkg/schema/schema_test.go
pkg/search/describe.go
pkg/search/handler.go
pkg/search/query.go
pkg/search/websocket.go
pkg/server/download.go
pkg/server/filetree.go
pkg/server/import_share.go
pkg/server/share.go
pkg/types/camtypes/search.go

pkg/schema: create CamliType type
Create a CamliType type in pkg/schema and use it in a couple of
packages.
It can be implemented in other packages as we go.
I was reading pkg/index and decided to implement @mpl's TODO:
```
// TODO(mpl): create consts somewhere for "claim" and "permanode" as camliTypes, and use them,		if meta.CamliType != string(schema.PermanodeCamliType) && meta.CamliType != string(schema.ClaimCamliType) {
// instead of hardcoding. Unless they already exist ? (didn't find them).
```

pkg/schema: create CamliType type

---

cmd/pk-put/init.go
pkg/jsonsign/keys.go
pkg/serverinit/genconfig.go
pkg/serverinit/testdata/gpg_fingerprint-want.json
pkg/serverinit/testdata/gpg_fingerprint.json

closes #1361
```
pk-put+perkeepd config: support fingerprints
- Key ids in the `0xXXXXXXXXXXXXXXXX` format are now accepted.
- Key ids in the `02A6 ACA0 5F16 9329 D94A  FFB8 C804 D0BA 9F70 883D`
format are also accepted. With or without spaces.
- Help texts now use long keyids so that its clear that we support
them.
```

pk-put+perkeepd config: support fingerprints

---

cmd/pk-put/delete.go

So that `delete` is listed under `pk put -help` examples.

delete.go: implement Examples()

---

Dockerfile

Closes https://github.com/perkeep/perkeep/issues/1372
Dockerfile: build using gomodules
- Don't ADD the vendor/ directory
- ADD go.mod and go.sum
- Bump Go to 1.15.7
- Style improvement: spaces -> tabs

Dockerfile: build using gomodules

---

pkg/client/client.go
pkg/jsonsign/keys.go
pkg/schema/sign.go

Noticed this while working on https://github.com/perkeep/perkeep/pull/1363.
I think we should use fingerprints as much as possible and revert to shorter ids only when necessary, possibly fully deprecating short ids if that is possible. This PR is one step towards this. I intend to open a couple of follow-up PRs improving on this, propagating fingerprints where it makes sense and using them as much as possible.
```
signer: deprecate KeyId()
`signer.KeyId()` was only used in a counter-productive way
by comparing it with half of a long ID.
Also use this opportunity to return the full fingerprint from
ParseArmoredPublicKey. NewSigner was the only caller of this
function.
```

signer: deprecate KeyId()

---

pkg/fs/fs_test.go
pkg/fs/root.go
pkg/test/world.go

fs: don't cause io errors on missing blobrefs
- Looking up missing blobrefs would cause fs errors. Instead, simply
return fuse.ENOENT.
- Add tests for:
* validating that the mountpoint/<blobref> lookups work
* validating that the mountpount/<blobref> lookups don't fail when
the blob does not exist.

fs: don't cause io errors on missing blobrefs

---

internal/osutil/paths.go
pkg/fs/fs_test.go

pkmountTest: ensure tests don't share cache
Also introduce PERKEEP_CACHE_DIR so we can deprecate CAMLI_CACHE_DIR
at some point.
I had a couple of cache issues while working on my previous fs patch. At some point I reverted my entire patch trying to debug why my tests were still failing until I realised that the tests were using my camlicache, causing unexpected behaviors.
This ensures that all mount tests have their own cache.

pkmountTest: ensure tests don't share cache

---

dev/devcam/hook.go

devcam hook: fix bad script path
This would create the hook at `.git/hookspre-commit` instead of creating
it at `.git/hooks/pre-commit`.

devcam hook: fix bad script path

---

.github/workflows/tests-lint.yaml
.github/workflows/tests-linux.yml
.github/workflows/tests-macos.yml
.github/workflows/tests-tidy.yaml
.github/workflows/tests-windows.yml
go.mod
go.sum
make.go
pkg/blobserver/encrypt/encrypt_test.go
pkg/search/describe_test.go

This will be required to move to go:embed.
Splitting it out in another PR to keep things light.

go 1.15 -> 1.16

---

pkg/jsonsign/verify.go
pkg/jsonsign/verify_test.go

reArmor was producing funny signatures :))
It looks like this has never caused issues, but lets fix it for exactness.

pkg/jsonsign: reArmor: BEGIN -> END

---

pkg/search/predicate.go
pkg/search/predicate_test.go

Re: https://groups.google.com/g/perkeep/c/rqHL4QmAxPg
Add `is:untagged` predicate to query untagged permanodes via the UI.

pkg/search: Add untagged predicate

---

pkg/jsonsign/sign.go
pkg/schema/sign.go

EntityFetcher: require fingerprint
EntityFetcher no longer supports key ids. This isn't required anymore as
its only user (`SignRequest.Sign()`) now passes fingerprints.

EntityFetcher: require fingerprint

---

pkg/fs/fs.go

Fixes #1573 
A context was forgotten to be propagated when bumping the `bazil.org/fuse` package.

fuse: fix panic in Lookup

---

pkg/server/download.go

Noticed this panic when scrolling: 
```
2022/02/23 17:56:57 http: panic serving 127.0.0.1:42996: runtime error: invalid memory address or nil pointer dereference
goroutine 11142 [running]:
net/http.(*conn).serve.func1(0xc0016a8000)
/var/home/mhoffm/sdk/go1.16.13/src/net/http/server.go:1805 +0x153
panic(0x14da160, 0x2576e70)
/var/home/mhoffm/sdk/go1.16.13/src/runtime/panic.go:971 +0x499
perkeep.org/pkg/server.fileInfoPacked(0x1c50250, 0xc000417cc0, 0xc0014c6400, 0x7f57181e9638, 0xc00015d340, 0x0, 0x1c58698, 0xc0009eea00, 0x0, 0x0, ...)
/var/home/mhoffm/Git/Tools/perkeep.org/pkg/server/download.go:256 +0x5ad
perkeep.org/pkg/server.(*ImageHandler).newFileReader(0xc0016c3830, 0x1c50250, 0xc000417cc0, 0x1c58698, 0xc0009eea00, 0xc000374ea8, 0xc001d15d70, 0xc001d15d70, 0xc0005c8780) …
```

server: fix panic when modtime or time is not in metadata

---

cmd/pk-put/camput_test.go
internal/osutil/paths_test.go
pkg/blobserver/diskpacked/stream_test.go
pkg/index/kvfile_test.go
pkg/index/leveldb_test.go
pkg/schema/schema_test.go
pkg/test/integration/camget_test.go
pkg/test/integration/camlistore_test.go
pkg/test/integration/camput_test.go
pkg/test/integration/non-utf8_test.go
pkg/test/integration/share_test.go

We can write less code by using the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir

all: use `T.TempDir` to create temporary directory

---

pkg/blobserver/gethandler/get.go

(First time contributing, and my Go is rusty!)
Considering the blob store is content-addressed, it seems to make sense to set a far-future caching header by default. The web UI should automatically benefit from this, too.
WDYT?

Set far-future caching header on blob responses

---

pkg/jsonsign/jsonsign_test.go
pkg/jsonsign/keys.go

```
jsonsign: write armored keyring
Write Perkeep's keyring as armored for simpler backup to text files.
The code is backwards-compatible. We try reading the keyring as if it
was armored and we default to the old format on failure.
```

jsonsign: write armored keyring

---

pkg/jsonsign/sign.go

pkg/sign: use local readKeyRing function instead of opengpg's, to handle armored key rings.

---

.dockerignore
Dockerfile

This updates the main perkeep Dockerfile in various ways (see individual commits) to improve both build time and image size by ~40% each.
I switched from running perkeep directly on Debian to Docker a few weeks ago with these changes, and it's been working well for me.  One small downside is that the distroless base image no longer has a shell that can be used to explore or debug the container, but I've personally never used that anyway.  Not sure if others have, hopefully that's okay?

improve docker build times and image size

---

doc/geocoding.md
internal/geocode/geocode.go
internal/geocode/geocode_test.go
pkg/server/help.go
server/perkeepd/perkeepd.go

Use the OpenStreetMap [Nominatim API](https://wiki.openstreetmap.org/wiki/Nominatim) when no Google Geocoding API key is present.  Nominatim does not require any keys, so we can safely enable it by default, though their terms request no more than 1 qps, which should probably be fine?
Docs and log messages are updated to reflect this behavior.  OSM Attribution is added to the help page, which is not the best but probably okay for now.  In a future change, I'd like to change the About alert to a static page, and move licensing information there.
Fixes #1342

geocode: add support for openstreetmap geocoding api

---

cmd/pk-mount/pkmount.go
cmd/pk-mount/pkmount_other.go
pkg/client/get.go
pkg/client/upload.go
pkg/fs/at.go
pkg/fs/debug.go
pkg/fs/fs.go
pkg/fs/fs_test.go
pkg/fs/mut.go
pkg/fs/mut_test.go
pkg/fs/recent.go
pkg/fs/ro.go
pkg/fs/root.go
pkg/fs/roots.go
pkg/fs/rover.go
pkg/fs/time.go
pkg/fs/time_test.go
pkg/fs/util.go
pkg/fs/versions.go
pkg/fs/xattr.go
pkg/fs/z_test.go
pkg/schema/filereader.go
pkg/schema/schema.go

This should fix some of the flakiness in the `perkeep.org/pkg/fs` tests.
* propagate more context cancelations from pkg/client
* convert ErrCancel to fuse.EINTR to enable clients to handle interrupts
* improve interrupt handling in fs_test.go
* fix race in mutdir between rename and first populate

fuse: misc fixes

---

pkg/client/client.go
pkg/importer/test/helpers.go
pkg/index/index_test.go
pkg/index/indextest/tests.go
pkg/index/receive.go

closes https://github.com/perkeep/perkeep/issues/1328
index: verify sigs on permanodes, not just claims
Index:
- Handle bad signatures on permanodes just like we handled them on
claims.
Importer tests:
- Make pkg/client's UploadPublicKey method public so that we can ensure
that the key was uploaded before uploading permanodes in importer
tests. This would otherwise be done automatically by methods such as
UploadNewPermanode but the importer uses the Blobserver API, it
uploads blobs with ReceiveBlob. ReceiveBlob does not know if blobs
are schemas or regular blobs, so it couldn't know if it is
appropriate to upload the key.

index: verify sigs on permanodes, not just claims

---

internal/images/fastjpeg/fastjpeg.go
internal/images/images.go

The test image crashed on my perkeep instance with 
```
Jul 09 12:14:01 ubuntu perkeepd[74240]: 2022/07/09 12:14:01 Retrying with jpeg.Decode, because djpeg failed with: exit status 2: Invalid SOS parameters for sequential JPEG
Jul 09 12:14:02 ubuntu perkeepd[74240]: 2022/07/09 12:14:02 http: panic serving 192.168.178.38:44074: runtime error: invalid memory address or nil pointer dereference
Jul 09 12:14:02 ubuntu perkeepd[74240]: goroutine 7711129 [running]:
Jul 09 12:14:02 ubuntu perkeepd[74240]: net/http.(*conn).serve.func1(0x4020f57e00)
Jul 09 12:14:02 ubuntu perkeepd[74240]:         /home/micha/.local/go/src/net/http/server.go:1802 +0xe4
Jul 09 12:14:02 ubuntu perkeepd[74240]: panic({0xea4340, 0x203d300})
Jul 09 12:14:02 ubuntu perkeepd[74240]: …
```

images: fix crash when decoding with djpeg fails

---

app/publisher/main.go
pkg/app/app.go
pkg/buildinfo/buildinfo.go
pkg/client/upload.go
pkg/server/app/app.go
pkg/server/wizard.go
pkg/types/camtypes/errors.go
pkg/types/serverconfig/config.go

fix up some links
There are still some references to camlistore.org that I don't understand so left alone.

camlistore.org -> perkeep.org

---

pkg/server/ui.go

`http.ServeContent` figures out the content type on its own, i also checked the headers in my browser with this patch (build with go1.19 though) . 
The comment changes comes from `go fmt`.

ui: remove obsolete code

---

cmd/pk-put/camput_test.go
internal/images/fastjpeg/fastjpeg_test.go
internal/osutil/paths_test.go
pkg/serverinit/serverinit_test.go

[T.Setenv](https://pkg.go.dev/testing#T.Setenv):
> Setenv calls os.Setenv(key, value) and uses Cleanup to restore the environment variable to its original value after the test.

tests: use T.Setenv instead of os.Setenv

---

.github/workflows/tests-linux.yml
cmd/pk-mount/pkmount.go
cmd/pk-mount/pkmount_other.go
go.mod
go.sum
pkg/fs/at.go
pkg/fs/debug.go
pkg/fs/fs.go
pkg/fs/fs_test.go
pkg/fs/mut.go
pkg/fs/mut_test.go
pkg/fs/recent.go
pkg/fs/ro.go
pkg/fs/root.go
pkg/fs/roots.go
pkg/fs/rover.go
pkg/fs/time.go
pkg/fs/time_test.go
pkg/fs/util.go
pkg/fs/versions.go
pkg/fs/xattr.go
pkg/fs/z_test.go

Bazil/fuse no longer supports macOS
(https://github.com/bazil/fuse/issues/224) because osxfuse is no
longer open source (https://github.com/osxfuse/osxfuse/issues/590).
Also, Apple is making it harder and harder (eventually impossible?) to
install custom kernel modules:
https://github.com/macfuse/macfuse/wiki/Getting-Started
So just give up on macOS FUSE support for now. We can resurrect it
later via WebDAV and/or NFS server support.
Signed-off-by: Brad Fitzpatrick <brad@danga.com>

cmd/pk-mount, pkg/fs: drop macOS FUSE support

---

clients/web/embed/closure/updatelibrary.go
dev/update_closure_compiler.go
internal/osutil/paths.go
misc/docker/dock.go
misc/release/make-release.go
pkg/importer/flickr/testdata.go
pkg/importer/picasa/testdata.go
pkg/importer/swarm/testdata.go
pkg/importer/twitter/testdata.go
pkg/index/indextest/tests.go
pkg/index/stress/index_test.go
pkg/search/describe_test.go
pkg/search/handler_test.go
pkg/search/query_test.go
pkg/server/ui.go
pkg/serverinit/serverinit_test.go
pkg/test/world.go

- move `PkSourceRoot` from `pkg/test/world.go` to `internal/osutil/paths.go`;
- migrate all calls from `osutil.GoPackagePath("perkeep.org")` to `osutil.PkSourceRoot()`;
- keep the variable name consistent (`camliRootPath`, `camDir`, etc. => `srcRoot`);
- The GOPATH way is still there as a fallback for compatibility.
Hi, 
While playing around to learn the code base, I tried to run the tests and got errors about `perkeep.org` not being in `GOPATH/src`. 
I thought it would be a good way to get acquainted with the code base. 
I hope I didn't overstep by changing too many things. 
All the tests are passing, including the integration tests.
Let me know what you would like to change in this PR, I'm just trying to be a good citizen. :)
For reference: https://go.dev/wiki/GOPATH

Tests: using GOMOD for the source root to run integration tests outside GOPATH
